;;; avocations.el --- Diversions and avocations.

;;; Commentary:
;; 


;;; Code:

(require 'malyon)
;; Major mode for playing z3/5/8 story files.
;;   https://en.wikipedia.org/wiki/Z-machine
;; This package provides a basic interpreter for version 3, 5, 8 z code
;; story files as generated by Inform (C) Graham Nelson and Infocom.
;; This mode allows execution of version 3, 5, 8 z code story files.
;; File examples could be in .emacs.d/games/z-machine.
;; http://www.ifarchive.org/

;; CHESS
;; To improve your chessaility, `M-x chess-tutorial' provides a simple knight
;; movement exercise to get you started, and `M-x chess-puzzle' can be used
;; to solve puzzle collections in EPD or PGN format.
(setq chess-default-display 'chess-images)
(setq chess-default-engine 'chess-gnuchess)

;; TETRIS
(defadvice tetris-end-game (around zap-scores activate)
  (save-window-excursion ad-do-it))

;; AI
;;; Write software to beat software.
(load  "~/.emacs.d/games/AI/autotetris-mode/autotetris-mode.elc")
;; Byte compiled from make.

(require 'turing-machine)
;;   Computing machine that can use a predefined set of rules to determine
;; a result from a set of input variables.

(provide 'avocations)

;;; avocations.el ends here
